### ISSUE TITLE
add eustis status checker

### ISSUE THREAD

**Issue by tgsachse** [tgsachse/lion#14]

**Comment by haydeninghem** [comment]
We looked into this and its not possible.

**Comment by tgsachse** [comment]
yea my guess would be the server im hosting on would have to be logged into the VPN with my credentials and be able to ping the server. Even then though that doesn't really confirm it is running. It's unfortunate that they dont host a webpage with the server's status.

**Comment by odxs** [comment]
The only way to do this is to share the same DNS servers that UCF has on their local network or for them to have a status page that we could just scrape. Maybe reaching out to someone in that dept. can be of use for this?
