### ISSUE TITLE
use bot spam channel mostly (standardize message interface)

### ISSUE THREAD

**Issue by tgsachse** [tgsachse/lion#35]
Delete original command and ping the user from bot spam.

Potential commands include addroles, removeroles, listroles, weather, garage, help, info, user count.

Leave dog, egg, poll, and sponge to execute in the same chat that they were requested in.

**Comment by tgsachse** [comment]
Ping the user like this:

@user:
<rest of the results>

**Comment by tgsachse** [comment]
Keep the botspam channel as a constant string in each plugin probably, something like

BOT_SPAM_CHANNEL = "bot_spam"

or you might even make a new Channel object using the discord package.

**Comment by tgsachse** [comment]
This will probably be easier with the new discord.py api.

**Comment by serspencer** [comment]
Tiger I have the fix, I can branch this repo add it and submit a PR if you want.

**Comment by serspencer** [comment]
I have a working copy of this on my fork

**Comment by tgsachse** [comment]
have a default channel/have standard formatting that is toggleable

**Comment by tgsachse** [comment]
all solved in latest version of rewrite
