### ISSUE TITLE
require users to !register for classes

### ISSUE THREAD

**Issue by tgsachse** [tgsachse/lion#36]
!register <course code> <professor>
!listcourses
--> display all classes available with course code and then professor

All other classes will be hidden! Greatly improves left side lists.

**Comment by tgsachse** [comment]
Example of !listcourses

```
poop leinecker
poop hollander
discrete1 vu
discrete1 boustique
```

or maybe with course codes

```
COPXXXX leinecker
COPXXXX hollander
COTXXXX boustique

```

**Comment by tgsachse** [comment]
Example of !register

```
!register cop4331 hollander
!register cot4210 boustique
```

Should not work:
```
!register cop4331
# no prof

!register coz4000
# class doesnt exist

!register cop4331 guha
# prof isnt teaching that class
```

I will change the names of the channel as needed. You can assume that the format of the channel name will be like this:
{course code or shorthand}_{all lowercase professor name}

We can decide on whether to use course codes or shorthand later.

**Comment by tgsachse** [comment]
So to get the full list of available course channels, ull have to loop thru the channels on the discord. I will also be moving all course channels into a single category called "CLASSES" or something once this is done, so you really only need to loop through one category, if that helps

**Comment by tgsachse** [comment]
Also I'd like it to support `!register all` for us admins/mods/whoever wants to view all the channels

**Comment by tgsachse** [comment]
So that we don't have to !register for 40 classes, that'd be a pain.

**Comment by c650** [comment]
Should allow for multiple arguments...

```
!register class_a class_b class_c
```

**Comment by tgsachse** [comment]
Also please include an !unregister or something similar to remove classes. Make sure they can't use it to !unregister general_chat etc

**Comment by c650** [comment]
so then only let this command group affect certain chan categories.
