### ISSUE TITLE
Make back end CLI

### ISSUE THREAD

**Issue by c650** [tgsachse/lion#62]
Back-end console to run administrative commands discretely. Good for configuring lots of channels at once.

**Comment by tgsachse** [comment]
Some flags:
```
--start
--stop
--restart
--enable
--disable
--add-cogs/--cogs
--token/--add-token
--enable-cogs
--disable-cogs
--log
--version
--announce
```

**Comment by c650** [comment]
Cogs are what we're calling the plugins?

**Comment by tgsachse** [comment]
In the rework im going to start calling them Cogs since thats what they are called internally in discord.py
