### ISSUE TITLE
Add administration cog

### ISSUE THREAD

**Issue by c650** [tgsachse/lion#63]
Kind of like #57 but specifically no down-time for new plugins or changes to any running plugins.

**Comment by tgsachse** [comment]
Dynamic plugin loading and unloading
Set default channel
restart bot

**Comment by tgsachse** [comment]
no dynamic plugin loading or unloading, this must be done server side (bc individual guilds cannot have different plugins loaded, and dont want individual guilds being able to mess with other guilds' plugin configurations)

**Comment by tgsachse** [comment]
Might even remove restart controls, because then 1 guild's admins could restart bot for all guilds which would be bad. Yikes.

**Comment by tgsachse** [comment]
will add more features as needed. For now only set default server has been implemented.
