### ISSUE TITLE
send message for commands being sent in wrong channels

### ISSUE THREAD

**Issue by odxs** [tgsachse/lion#64]
When a user types (for example) `!register all` in a channel that is not `#bot_spam`, lion should send either a DM to the user or message to the channel stating something along the lines of:
`Hey! This command is not supported within this channel. Please utilize this command within #bot_spam`

**Comment by serspencer** [comment]
I have implemented this in my fork.

**Comment by tgsachse** [comment]
The rewrite will handle this differently. Don't worry about it for now.
